### ISSUE TITLE
An error

### ISSUE THREAD

**Issue by ZinhoYip** [SDmodding/ModelScriber#1]
D:\Sources\SDmodding\theory_tools\ModelScriber> ModelScriberPC64 -fbx "D:\Sources\SDmodding\theory_tools\ModelScriber\CJ.fbx" -vertexdecl Skinned
WARNING:  Could not create directory 'D:\Sources\SDmodding\theory_tools\ModelScriber\CJ.perm.bin' when opening 'D:\Sources\SDmodding\theory_tools\ModelScriber\CJ.perm.bin'.  Current Dir = 'D:\Sources\SDmodding\theory_tools\ModelScriber'
ERROR: Unable to open file = 'D:\Sources\SDmodding\theory_tools\ModelScriber\CJ.perm.bin'

*********************************
********** ASSERT FAIL **********
*********************************
D:\Sources\SDmodding\theory_tools\ModelScriber\ModelScriber\theory\quark\resourcefile_impl.hh(339):
CONDITION = mBuildType != BUILDTYPE_CREATE

**Comment by sneakyevil** [comment]
This was bug in theory engine implementation missing `PCFileDevice::CreateDirectoryA` implementation and causing assert due to directory been always invalid. Download latest release for fix.
